/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hughes.android.dictionary;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int DownButton=0x7f06000d;
        public static final int ImageView01=0x7f060002;
        public static final int LangButton=0x7f06000c;
        public static final int LinearLayout01=0x7f060000;
        public static final int LinearLayout02=0x7f060001;
        public static final int SearchBarLinearLayout=0x7f060008;
        public static final int SearchBarTableLayout=0x7f060009;
        public static final int SearchBarTableRow=0x7f06000a;
        public static final int SearchText=0x7f06000b;
        public static final int UpButton=0x7f06000e;
        public static final int author=0x7f060006;
        public static final int copyright=0x7f060005;
        public static final int email=0x7f060007;
        public static final int space1=0x7f060004;
        public static final int title=0x7f060003;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about_text=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int dictFetchUrl=0x7f050004;
        public static final int dictFile=0x7f050003;
        public static final int wordListFile=0x7f050002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
