/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hughes.android.dictionary;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int DownButton=0x7f050005;
        public static final int LangButton=0x7f050004;
        public static final int SearchBarLinearLayout=0x7f050000;
        public static final int SearchBarTableLayout=0x7f050001;
        public static final int SearchBarTableRow=0x7f050002;
        public static final int SearchText=0x7f050003;
        public static final int UpButton=0x7f050006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
