/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hughes.android.dictionary;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int DownButton=0x7f06001b;
        public static final int ImageView01=0x7f060002;
        public static final int LangButton=0x7f06001a;
        public static final int LinearLayout01=0x7f060000;
        public static final int LinearLayout02=0x7f060001;
        public static final int SearchBarLinearLayout=0x7f060016;
        public static final int SearchBarTableLayout=0x7f060017;
        public static final int SearchBarTableRow=0x7f060018;
        public static final int SearchText=0x7f060019;
        public static final int TextView01=0x7f06000d;
        public static final int UpButton=0x7f06001c;
        public static final int author=0x7f060006;
        public static final int copyright=0x7f060005;
        public static final int currentDictInfo=0x7f06000c;
        public static final int currentDictInfoTitle=0x7f06000b;
        public static final int dest=0x7f060013;
        public static final int destLayout=0x7f060011;
        public static final int destTitle=0x7f060012;
        public static final int downloadProgressBar=0x7f060014;
        public static final int downloadStatus=0x7f060015;
        public static final int email=0x7f060009;
        public static final int emailMe=0x7f060008;
        public static final int source=0x7f060010;
        public static final int sourceLayout=0x7f06000e;
        public static final int sourceTitle=0x7f06000f;
        public static final int space1=0x7f060004;
        public static final int space2=0x7f06000a;
        public static final int space3=0x7f060007;
        public static final int title=0x7f060003;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int download=0x7f030001;
        public static final int main=0x7f030002;
    }
    public static final class string {
        public static final int about_text=0x7f050001;
        public static final int app_name=0x7f050000;
        public static final int dictFetchUrl=0x7f050007;
        public static final int dictFetchUrlKey=0x7f050006;
        public static final int dictFile=0x7f050005;
        public static final int dictFileKey=0x7f050004;
        public static final int wordListFile=0x7f050003;
        public static final int wordListFileKey=0x7f050002;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
